make build failure artefact conditional for nfssext-needy (but not archiving already?)

diff --git a/.github/workflows/nfssext-autochecks.yml b/.github/workflows/nfssext-autochecks.yml
--- a/.github/workflows/nfssext-autochecks.yml
+++ b/.github/workflows/nfssext-autochecks.yml
@@ -276,9 +276,11 @@ jobs:
       - name: Run l3build fnttarg
         if: ${{ matrix.pre_target }}
         working-directory: ${{ matrix.working_directory }}
-        run: "l3build fnttarg"
+        id: fnttarg
+        run: (l3build fnttarg && echo -e "BUILD_RET=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1" >> "$GITHUB_OUTPUT"
       - name: Archive failed build output
-        if: ${{ matrix.pre_target }}
+      # run even iff previous step failed
+        if: ${{ !cancelled() && !(steps.fnttarg.outputs.BUILD_RET) && matrix.pre_target }}
       # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
         uses: actions/upload-artifact@v4
         with:
