here goes nothing ...

diff --git a/.github/workflows/nfssext-release.yml b/.github/workflows/nfssext-release.yml
--- a/.github/workflows/nfssext-release.yml
+++ b/.github/workflows/nfssext-release.yml
@@ -44,8 +44,10 @@ jobs:
     needs: texlive-cache
     # nfssext-cfr uses cfr-lm (though it falls back if built first)
     # cfr-lm uses nfssext-cfr but there's nothing to build
-    # outputs:
+    outputs:
     #   clm_cache_key: $(( steps.clm-cache.outputs.cache_key }}
+      fnttarg_clm_output: ${{ steps.fnttarg-clm.outputs.build_ret_clm }}
+      ctan_clm_output: ${{ steps.ctan-clm.outputs.ctan_ret_clm }}
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout repo
@@ -67,7 +69,10 @@ jobs:
       - name: Run l3build fnttarg 
         id: fnttarg-clm
         working-directory: cfr-lm
-        run: (l3build fnttarg && echo "BUILD_RET=0" >> "$GITHUB_OUTPUT") || echo "BUILD_RET=1" >> "$GITHUB_OUTPUT"
+        # run: (l3build fnttarg && echo "BUILD_RET=0" >> "$GITHUB_OUTPUT") || echo "BUILD_RET=1" >> "$GITHUB_OUTPUT"
+        run: |
+          (l3build fnttarg && echo -e "BUILD_RET=0\nbuild_ret_clm=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nbuild_ret_clm=1" >> "$GITHUB_OUTPUT"
+          cat "$GITHUB_OUTPUT"
       - name: Archive failed build output
       # run even iff previous step failed
         if: ${{ !cancelled() && !(steps.fnttarg-clm.outputs.BUILD_RET) }}
@@ -79,17 +84,22 @@ jobs:
           # Decide how long to keep the test output artefact:
           retention-days: 7
       - name: Create manifest
-        if: ${{ contains(github.ref_name, 'cfr-lm-') || contains(github.ref_name, 'clm-') }}
+        if: ${{ (contains(github.ref_name, 'cfr-lm-') || contains(github.ref_name, 'clm-')) && (steps.fnttarg-clm.outputs_BUILD_RET) }}
         working-directory: cfr-lm
         run: l3build check && l3build doc && l3build manifest
       - name: Run l3build ctan 
+        if: ${{ !cancelled() && (steps.fnttarg-clm.outputs.BUILD_RET) }}
         working-directory: cfr-lm
-        run: l3build ctan
-      - name: Run l3build install 
-        working-directory: cfr-lm
-        run: l3build install
-      - name: Update map
-        run: updmap --user --enable Map=clm.map
+        # run: l3build ctan
+        id: ctan-clm
+        run: |
+          (l3build ctan && echo -e "CTAN_RET=0\nctan_ret_clm=0" >> "$GITHUB_OUTPUT") || echo -e "CTAN_RET=1\nctan_ret_clm=1" >> "$GITHUB_OUTPUT"
+          cat "$GITHUB_OUTPUT"
+      # - name: Run l3build install 
+      #   working-directory: cfr-lm
+      #   run: l3build install
+      # - name: Update map
+      #   run: updmap --user --enable Map=clm.map
       - name: Archive failed test output for clm
         # run even if previous step failed
         if: ${{ !cancelled() }}
@@ -98,20 +108,20 @@ jobs:
           name: testfiles-clm
           # Decide how long to keep the test output artefact:
           retention-days: 7
-      - name: Cache build results
-        id: clm-cache
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            ~/.texlive
-            ~/texmf
-          key: clm-${{ github.sha }}
+      # - name: Cache build results
+      #   id: clm-cache
+      #   uses: actions/cache/save@v4
+      #   with:
+      #     path: |
+      #       ~/.texlive
+      #       ~/texmf
+      #     key: clm-${{ github.sha }}
       - name: List zip
         if: ${{ contains(github.ref_name, 'cfr-lm-') || contains(github.ref_name, 'clm-') }}
         run: |
           unzip -l cfr-lm/cfr-lm-ctan.zip
       - name: Archive zip
-        if: ${{ contains(github.ref_name, 'cfr-lm-') || contains(github.ref_name, 'clm-') }}
+        if: ${{ (contains(github.ref_name, 'cfr-lm-') || contains(github.ref_name, 'clm-')) && (steps.ctan-clm.outputs_CTAN_RET) }}
         # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
         uses: actions/upload-artifact@v4
         with:
@@ -143,7 +153,7 @@ jobs:
     # don't abandon other builds if one module fails
     # continue-on-error: true
     strategy:
-      fail-fast: false
+      # fail-fast: false
       matrix:
         # include indicates that we want to set explicitly these combinations
         # and don't want full matrix testing.
@@ -180,7 +190,6 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
       # https://github.com/josephwright/siunitx/blob/549cad913591b92a3a199b7477a325866303bf29/.github/workflows/main.yaml
-      # We need Ghostscript for XeTeX tests.
       - name: Update system 
         run: sudo apt-get update
       - name: Install additional packages if needed
@@ -223,7 +232,7 @@ jobs:
         id: ctan
         run: |
           module="${{ matrix.module }}"
-          (l3build ctan && echo -e "BUILD_RET=0\nctan_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nctan_ret_${module}=1" >> "$GITHUB_OUTPUT"
+          (l3build ctan && echo -e "CTAN_RET=0\nctan_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "CTAN_RET=1\nctan_ret_${module}=1" >> "$GITHUB_OUTPUT"
           cat "$GITHUB_OUTPUT"
       - name: Archive failed test output
       # run even if previous step failed
@@ -267,7 +276,7 @@ jobs:
     # don't abandon other builds if one module fails
     # continue-on-error: true
     strategy:
-      fail-fast: false
+      # fail-fast: false
       matrix:
         # include indicates that we want to set explicitly these combinations
         # and don't want full matrix testing.
@@ -309,15 +318,15 @@ jobs:
         # oes!
       - name: Set PATH
         run: echo $HOME/texlive/bin/x86_64-linux >> $GITHUB_PATH
-      - name: Restore cfr-lm from cache
-        if: ${{ matrix.extra_needs }}
-        uses: actions/cache/restore@v4
-        with:
-          path: |
-            ~/.texlive
-            ~/texmf
-          key: clm-${{ github.sha }}
-          fail-on-cache-miss: true
+      # - name: Restore cfr-lm from cache
+      #   if: ${{ matrix.extra_needs }}
+      #   uses: actions/cache/restore@v4
+      #   with:
+      #     path: |
+      #       ~/.texlive
+      #       ~/texmf
+      #     key: clm-${{ github.sha }}
+      #     fail-on-cache-miss: true
       - name: Run l3build fnttarg
         if: ${{ matrix.pre_target }}
         working-directory: ${{ matrix.working_directory }}
@@ -327,7 +336,7 @@ jobs:
           (l3build fnttarg && echo -e "BUILD_RET=0\nbuild_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nbuild_ret_${module}=1" >> "$GITHUB_OUTPUT"
           cat "$GITHUB_OUTPUT"
       - name: Archive failed build output
-      # run even iff previous step failed
+      # run iff previous step failed
         if: ${{ !cancelled() && !(steps.fnttarg.outputs.BUILD_RET) && matrix.pre_target }}
       # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
         uses: actions/upload-artifact@v4
@@ -345,7 +354,7 @@ jobs:
         id: ctan
         run: |
           module="${{ matrix.module }}"
-          (l3build ctan && echo -e "BUILD_RET=0\nctan_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nctan_ret_${module}=1" >> "$GITHUB_OUTPUT"
+          (l3build ctan && echo -e "CTAN_RET=0\nctan_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "CTAN_RET=1\nctan_ret_${module}=1" >> "$GITHUB_OUTPUT"
           cat "$GITHUB_OUTPUT"
       - name: Archive failed test output
       # run even if previous step failed
@@ -377,13 +386,15 @@ jobs:
 
   summary:
     name: summary
-    needs: [ nfssext, nfssext-needy ]
+    needs: [ clm, nfssext, nfssext-needy ]
     if: ${{ !cancelled() }}
     runs-on: ubuntu-latest
     steps:
       - name: NFSSEXT Autochecks Summary
       # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
         env:
+          fnttargclm: ${{ needs.clm.outputs.fnttarg_clm_output }}
+          ctanclm: ${{ needs.clm.outputs.ctan_clm_output }}
           fnttargbaskervaldadf: ${{ needs.nfssext.outputs.fnttarg_baskervaldadf_output }}
           fnttargberenisadf: ${{ needs.nfssext.outputs.fnttarg_berenisadf_output }}
           fnttargelectrumadf: ${{ needs.nfssext.outputs.fnttarg_electrumadf_output }}
@@ -403,7 +414,7 @@ jobs:
           ctanfontscripts: ${{ needs.nfssext-needy.outputs.ctan_fontscripts_output }}
           ctannfssextcfr: ${{ needs.nfssext-needy.outputs.ctan_nfssext_cfr_output }}
         run: |
-          ([[ $fnttargbaskervaldadf != 0 || $fnttargberenisadf != 0 || $fnttargelectrumadf != 0 || $fnttarglibrisadf != 0 || $fnttargromandeadf != 0 || $fnttargventurisadf != 0 || $ctanbaskervaldadf != 0 || $ctanberenisadf != 0 || $ctanelectrumadf != 0 || $ctanlibrisadf != 0 || $ctanromandeadf != 0 || $ctanventurisadf != 0 || $fnttargadforn != 0 || $fnttargadfsymbols != 0 || $ctanadforn != 0 || $ctanadfsymbols != 0 || $ctanfontscripts != 0 || $ctannfssextcfr != 0 ]] && echo -e "BUILD_RET=1" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=0" >> "$GITHUB_OUTPUT"
+          ([[ $fnttargclm != 0 || $ctanclm != 0 || $fnttargbaskervaldadf != 0 || $fnttargberenisadf != 0 || $fnttargelectrumadf != 0 || $fnttarglibrisadf != 0 || $fnttargromandeadf != 0 || $fnttargventurisadf != 0 || $ctanbaskervaldadf != 0 || $ctanberenisadf != 0 || $ctanelectrumadf != 0 || $ctanlibrisadf != 0 || $ctanromandeadf != 0 || $ctanventurisadf != 0 || $fnttargadforn != 0 || $fnttargadfsymbols != 0 || $ctanadforn != 0 || $ctanadfsymbols != 0 || $ctanfontscripts != 0 || $ctannfssextcfr != 0 ]] && echo -e "BUILD_RET=1" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=0" >> "$GITHUB_OUTPUT"
           cat "$GITHUB_OUTPUT"
 
 
