h1

diff --git a/.github/workflows/nfssext-autochecks.yml b/.github/workflows/nfssext-autochecks.yml
--- a/.github/workflows/nfssext-autochecks.yml
+++ b/.github/workflows/nfssext-autochecks.yml
@@ -368,12 +368,11 @@ jobs:
       - name: Run l3build
         working-directory: ${{ matrix.working_directory }}
         id: ctan
+          # (l3build ctan && (echo -e "ctan_ret_${module}=0" >> "$GITHUB_OUTPUT" ; echo -e "CTAN_RET=0 >> "$GITHUB_ENV") || (echo -e "ctan_ret_${module}=1" >> "$GITHUB_OUTPUT" ; echo "CTAN_RET=1" >> "$GITHUB_ENV"))
         run: |
           module="${{ matrix.module }}"
-          (l3build ctan && ((echo -e "ctan_ret_${module}=0" >> "$GITHUB_OUTPUT") && CTAN_RET=0)) || ((echo -e "ctan_ret_${module}=1" >> "$GITHUB_OUTPUT") && CTAN_RET=1)
+          (l3build ctan && (echo -e "ctan_ret_${module}=0" >> "$GITHUB_OUTPUT" ; echo -e "CTAN_RET=0 >> "$GITHUB_OUPUT") || (echo -e "ctan_ret_${module}=1" >> "$GITHUB_OUTPUT" ; echo "CTAN_RET=1" >> "$GITHUB_OUPUT"))
           cat "$GITHUB_OUTPUT"
-          echo "CTAN_RET is $CTAN_RET"
-          [[ $CTAN_RET != 0 ]] && exit 1
       - name: Archive failed test output
       # run even if previous step failed
         if: ${{ !cancelled() }}
@@ -385,7 +384,10 @@ jobs:
       - name: Archive failed docs output
       # run even iff previous step failed
       # https://docs.github.com/en/actions/reference/evaluate-expressions-in-workflows-and-actions#status-check-functions
-        if: ${{ !cancelled() && steps.ctan.conclusion == 'failure' }}
+        # if: ${{ !cancelled() && steps.ctan.conclusion == 'failure' }}
+        if: ${{ !cancelled() && !(steps.ctan.outputs.CTAN_RET) && matrix.pre_target }}
+        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
+        # if: ${{ !cancelled() && !(${CTAN_RET}) && matrix.pre_target }}
       # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
         uses: actions/upload-artifact@v4
         with:
