info

diff --git a/.github/workflows/nfssext-autochecks.yml b/.github/workflows/nfssext-autochecks.yml
--- a/.github/workflows/nfssext-autochecks.yml
+++ b/.github/workflows/nfssext-autochecks.yml
@@ -86,10 +86,13 @@ jobs:
       - name: Run l3build fnttarg 
         id: fnttarg-clm
         working-directory: cfr-lm
-        # run: (l3build fnttarg && echo "BUILD_RET=0" >> "$GITHUB_OUTPUT") || echo "BUILD_RET=1" >> "$GITHUB_OUTPUT"
+          # (l3build fnttarg && echo -e "BUILD_RET=0\nbuild_ret_clm=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nbuild_ret_clm=1" >> "$GITHUB_OUTPUT"
         run: |
-          (l3build fnttarg && echo -e "BUILD_RET=0\nbuild_ret_clm=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nbuild_ret_clm=1" >> "$GITHUB_OUTPUT"
+          allan=0
+          l3build fnttarg || allan=1
+          echo -e "BUILD_RET=${allan}\nbuild_ret_clm=${allan}" >> "$GITHUB_OUTPUT"
           cat "$GITHUB_OUTPUT"
+          exit $allan
       - name: Archive failed build output
       # run iff previous step failed
         if: ${{ !cancelled() && !(steps.fnttarg-clm.outputs.BUILD_RET) }}
@@ -106,23 +109,46 @@ jobs:
         working-directory: cfr-lm
         id: ctan-clm
         run: | 
-          (l3build ctan && echo -e "CTAN_RET=0\nctan_ret_clm=0" >> "$GITHUB_OUTPUT") || echo -e "CTAN_RET=1\nctan_ret_clm=1" >> "$GITHUB_OUTPUT"
+          allan=0
+          l3build ctan || allan=1
+          # (l3build ctan && echo -e "CTAN_RET=0\nctan_ret_clm=0" >> "$GITHUB_OUTPUT") || echo -e "CTAN_RET=1\nctan_ret_clm=1" >> "$GITHUB_OUTPUT"
+          echo -e "CTAN_RET=${allan}\nctan_ret_clm=${allan}" >> "$GITHUB_OUTPUT" 
           cat "$GITHUB_OUTPUT"
+          exit "$allan"
+      - name: Archive failed docs output
+      # run even iff previous step failed
+      # https://docs.github.com/en/actions/reference/evaluate-expressions-in-workflows-and-actions#status-check-functions
+      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
+      # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
+        if: ${{ !cancelled() && steps.ctan-clm.outcome == 'failure' }}
+        # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
+        uses: actions/upload-artifact@v4
+        with:
+          name: typeset-logs-clm
+          path: build/doc/*.log
+          # Decide how long to keep the test output artefact:
+          retention-days: 7
       - name: Run l3build install 
       # run only if ctan succeeded
-        if: ${{ !cancelled() && (steps.ctan-clm.outputs.CTAN_RET) }}
+        if: ${{ !cancelled() && steps.ctan-clm.outcome == 'success' }}
         working-directory: cfr-lm
         id: install-clm
         run: |
-          (l3build install && echo "INSTALL_RET=0" >> "$GITHUB_OUTPUT") || echo "INSTALL_RET=1" >> "$GITHUB_OUTPUT"
+          allan=0
+          l3build install || allan=1
+          echo "INSTALL_RET=${allan}" >> "$GITHUB_OUTPUT" 
           cat "$GITHUB_OUTPUT"
+          exit $allan
       - name: Update map
       # run only if install succeeded
         if: ${{ !cancelled() && (steps.install-clm.outputs.INSTALL_RET) }}
         id: updmap-clm
         run: |
-          (updmap --user --enable Map=clm.map && echo "UPDMAP_RET=0" >> "$GITHUB_OUTPUT") || echo "UPDMAP_RET=1" >> "GITHUB_OUTPUT"
+          allan=0
+          updmap --user --enable Map=clm.map || allan=1
+          echo "UPDMAP_RET=${allan}" >> "$GITHUB_OUTPUT" 
           cat "$GITHUB_OUTPUT"
+          exit $allan
       - name: Archive failed test output for clm
         # run even if previous step failed
         if: ${{ !cancelled() }}
@@ -131,15 +157,23 @@ jobs:
           name: testfiles-clm
           # Decide how long to keep the test output artefact:
           retention-days: 7
-      - name: Cache build results
+      - name: Debug info
       # run only if updmap succeeded
         if: ${{ !cancelled() && (steps.updmap-clm.outputs.UPDMAP_RET) }}
+        run: |
+          ls -R ~/.texlive ~/texmf ~/work/nfssext/nfssext/cfr-lm/keep
+          kpsewhich clm.map
+      - name: Cache build results
+      # run only if build succeeded
+        if: ${{ !cancelled() && (steps.fnttarg-clm.outputs.BUILD_RET) }}
         id: clm-cache
         uses: actions/cache/save@v4
         with:
-          path: |
-            ~/.texlive
-            ~/texmf
+          path: ~/work/nfssext/nfssext/cfr-lm/keep
+          # path: |
+            # ~/work/nfssext/nfssext/cfr-lm/keep
+            # ~/.texlive
+            # ~/texmf
           key: clm-${{ github.sha }}
       - name: Archive docs
       # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
@@ -228,7 +262,9 @@ jobs:
         id: fnttarg
         run: |
           module="${{ matrix.module }}"
-          (l3build fnttarg && echo -e "BUILD_RET=0\nbuild_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nbuild_ret_${module}=1" >> "$GITHUB_OUTPUT"
+          allan=0
+          l3build fnttarg || allan=1
+          echo -e "BUILD_RET=${allan}\nbuild_ret_${module}=${allan}" >> "$GITHUB_OUTPUT" 
           cat "$GITHUB_OUTPUT"
       - name: Archive failed build output
       # run even iff previous step failed
@@ -245,14 +281,30 @@ jobs:
         id: ctan
         run: |
           module="${{ matrix.module }}"
-          (l3build ctan && echo -e "CTAN_RET=0\nctan_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "CTAN_RET=1\nctan_ret_${module}=1" >> "$GITHUB_OUTPUT"
+          allan=0
+          l3build ctan || allan=1
+          echo -e "CTAN_RET=${allan}\nctan_ret_${module}=${allan}" >> "$GITHUB_OUTPUT" 
           cat "$GITHUB_OUTPUT"
+          exit "$allan"
       - name: Archive failed test output
       # run even if previous step failed
         if: ${{ !cancelled() }}
         uses: zauguin/l3build-failure-artifacts@v1
         with:
           name: testfiles-${{ matrix.module }}
+          # Decide how long to keep the test output artefact:
+          retention-days: 7
+      - name: Archive failed docs output
+      # run even iff previous step failed
+      # https://docs.github.com/en/actions/reference/evaluate-expressions-in-workflows-and-actions#status-check-functions
+      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
+      # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
+        if: ${{ !cancelled() && steps.ctan.outcome == 'failure' }}
+        # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
+        uses: actions/upload-artifact@v4
+        with:
+          name: typeset-logs-${{ matrix.module }}
+          path: build/doc/*.log
           # Decide how long to keep the test output artefact:
           retention-days: 7
       - name: Archive docs
@@ -327,24 +379,29 @@ jobs:
         if: ${{ matrix.extra_needs }}
         uses: actions/cache/restore@v4
         with:
-          path: |
-            ~/.texlive
-            ~/texmf
+          path: ~/work/nfssext/nfssext/cfr-lm/keep
           key: clm-${{ github.sha }}
           fail-on-cache-miss: true
-      - name: Update map
-        id: updmap-clm
-        run: |
-          (updmap --user --enable Map=clm.map && echo "UPDMAP_RET=0" >> "$GITHUB_OUTPUT") || echo "UPDMAP_RET=1" >> "GITHUB_OUTPUT"
-          cat "$GITHUB_OUTPUT"
+      # - name: Update map
+      #   id: updmap-clm
+      #   run: |
+      #     (updmap --user --enable Map=clm.map && echo "UPDMAP_RET=0" >> "$GITHUB_OUTPUT") || echo "UPDMAP_RET=1" >> "GITHUB_OUTPUT"
+      #     cat "$GITHUB_OUTPUT"
+      # - name: Debug info
+      #   run: |
+      #     ls -R ~/.texlive ~/texmf ~/work/nfssext/nfssext/cfr-lm/keep
+      #     kpsewhich clm.map
       - name: Run l3build fnttarg
         if: ${{ matrix.pre_target }}
         working-directory: ${{ matrix.working_directory }}
         id: fnttarg
         run: |
           module="${{ matrix.module }}"
-          (l3build fnttarg && echo -e "BUILD_RET=0\nbuild_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=1\nbuild_ret_${module}=1" >> "$GITHUB_OUTPUT"
+          allan=0
+          l3build fnttarg || allan=1
+          echo -e "BUILD_RET=${allan}\nbuild_ret_${module}=${allan}" >> "$GITHUB_OUTPUT" 
           cat "$GITHUB_OUTPUT"
+          exit $allan
       - name: Archive failed build output
       # run even iff previous step failed
         if: ${{ !cancelled() && !(steps.fnttarg.outputs.BUILD_RET) && matrix.pre_target }}
@@ -360,14 +417,41 @@ jobs:
         id: ctan
         run: |
           module="${{ matrix.module }}"
-          (l3build ctan && echo -e "CTAN_RET=0\nctan_ret_${module}=0" >> "$GITHUB_OUTPUT") || echo -e "CTAN_RET=1\nctan_ret_${module}=1" >> "$GITHUB_OUTPUT"
+          allan=0
+          l3build ctan || allan=1
+          echo -e "CTAN_RET=${allan}\nctan_ret_${module}=${allan}" >> "$GITHUB_OUTPUT" 
           cat "$GITHUB_OUTPUT"
+          exit "$allan"
       - name: Archive failed test output
       # run even if previous step failed
         if: ${{ !cancelled() }}
         uses: zauguin/l3build-failure-artifacts@v1
         with:
           name: testfiles-${{ matrix.module }}
+          # Decide how long to keep the test output artefact:
+          retention-days: 7
+      # - name: Retrieve ctan build result
+      #   if: ${{ !cancelled() }}
+      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
+        # env:
+        #   CTAN_RET: ${{ steps.ctan.outputs.CTAN_RET }}
+        #   https://docs.github.com/en/actions/reference/accessing-contextual-information-about-workflow-runs#steps-context
+        # id: retrieve
+        # run: |
+        #   if [[ ${{ steps.ctan.outputs.CTAN_RET }} != 0 ]]; then exit 1; else exit 0; fi
+      - name: Archive failed docs output
+      # run even iff previous step failed
+      # https://docs.github.com/en/actions/reference/evaluate-expressions-in-workflows-and-actions#status-check-functions
+        # if: ${{ !cancelled() && steps.retrieve.outcome == 'failure' }}
+        if: ${{ !cancelled() && steps.ctan.outcome == 'failure' }}
+        # if: ${{ !cancelled() && !(steps.ctan.outputs.CTAN_RET) && matrix.pre_target }}
+        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
+        # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
+      # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
+        uses: actions/upload-artifact@v4
+        with:
+          name: typeset-logs-${{ matrix.module }}
+          path: build/doc/*.log
           # Decide how long to keep the test output artefact:
           retention-days: 7
       - name: Archive docs
@@ -410,8 +494,11 @@ jobs:
           ctanfontscripts: ${{ needs.nfssext-needy.outputs.ctan_fontscripts_output }}
           ctannfssextcfr: ${{ needs.nfssext-needy.outputs.ctan_nfssext_cfr_output }}
         run: |
-          ([[ $fnttargclm != 0 || $ctanclm != 0 || $fnttargbaskervaldadf != 0 || $fnttargberenisadf != 0 || $fnttargelectrumadf != 0 || $fnttarglibrisadf != 0 || $fnttargromandeadf != 0 || $fnttargventurisadf != 0 || $ctanbaskervaldadf != 0 || $ctanberenisadf != 0 || $ctanelectrumadf != 0 || $ctanlibrisadf != 0 || $ctanromandeadf != 0 || $ctanventurisadf != 0 || $fnttargadforn != 0 || $fnttargadfsymbols != 0 || $ctanadforn != 0 || $ctanadfsymbols != 0 || $ctanfontscripts != 0 || $ctannfssextcfr != 0 ]] && echo -e "BUILD_RET=1" >> "$GITHUB_OUTPUT") || echo -e "BUILD_RET=0" >> "$GITHUB_OUTPUT"
-          cat "$GITHUB_OUTPUT"
+          allan=0
+          ([[ $fnttargclm != 0 || $ctanclm != 0 || $fnttargbaskervaldadf != 0 || $fnttargberenisadf != 0 || $fnttargelectrumadf != 0 || $fnttarglibrisadf != 0 || $fnttargromandeadf != 0 || $fnttargventurisadf != 0 || $ctanbaskervaldadf != 0 || $ctanberenisadf != 0 || $ctanelectrumadf != 0 || $ctanlibrisadf != 0 || $ctanromandeadf != 0 || $ctanventurisadf != 0 || $fnttargadforn != 0 || $fnttargadfsymbols != 0 || $ctanadforn != 0 || $ctanadfsymbols != 0 || $ctanfontscripts != 0 || $ctannfssextcfr != 0 ]]) && allan=1
+          echo "Summary status: $allan"
+          echo -e "BUILD_RET=${allan}" >> "$GITHUB_OUTPUT" 
+          exit "$allan"
 
 
 # vim: sw=2:et:ts=2:
