hm

diff --git a/.github/workflows/nfssext-autochecks.yml b/.github/workflows/nfssext-autochecks.yml
--- a/.github/workflows/nfssext-autochecks.yml
+++ b/.github/workflows/nfssext-autochecks.yml
@@ -74,8 +74,8 @@ jobs:
         working-directory: cfr-lm
         run: (l3build fnttarg && echo "BUILD_RET=0" >> "$GITHUB_OUTPUT") || echo "BUILD_RET=1" >> "$GITHUB_OUTPUT"
       - name: Archive failed build output
-      # run even if previous step failed
-        if: ${{ !cancelled() && steps.fnttarg-clm.outputs.BUILD_RET }}
+      # run even iff previous step failed
+        if: ${{ !cancelled() && !(steps.fnttarg-clm.outputs.BUILD_RET) }}
       # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
         uses: actions/upload-artifact@v4
         with:
@@ -133,24 +133,31 @@ jobs:
           - module: baskervaldadf
             working_directory: arkandis/baskervaldadf
             pre_target: fnttarg
+            fnttarg_id: fnttarg-baskervaldadf
           - module: berenisadf
             working_directory: arkandis/berenisadf
             # berenis needs make, ff
             extra_packages: make fontforge
             pre_target: fnttarg
+            fnttarg_id: fnttarg-berenisadf
           - module: electrumadf
             working_directory: arkandis/electrumadf
             pre_target: fnttarg
+            fnttarg_id: fnttarg-electrumadf
           - module: librisadf
             working_directory: arkandis/librisadf
             pre_target: fnttarg
+            fnttarg_id: fnttarg-librisadf
           - module: romandeadf
             working_directory: arkandis/romandeadf
             pre_target: fnttarg
+            fnttarg_id: fnttarg-romandeadf
           - module: venturisadf
             working_directory: arkandis/venturisadf
             pre_target: fnttarg
+            fnttarg_id: fnttarg-venturisadf
     name: "Test build: ${{ matrix.module }}"
+    fnttarg_id_full: "steps.${{ matrix.fnttarg_id }}.outputs.BUILD_RET"
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout repo
@@ -175,10 +182,11 @@ jobs:
       - name: Run l3build fnttarg
         if: ${{ matrix.pre_target }}
         working-directory: ${{ matrix.working_directory }}
-        run: "l3build fnttarg"
+        id: ${{ matrix.fnttarg_id }}
+        run: (l3build fnttarg && echo "BUILD_RET=0" >> "$GITHUB_OUTPUT") || echo "BUILD_RET=1" >> "$GITHUB_OUTPUT"
       - name: Archive failed build output
-      # run even if previous step failed
-        if: ${{ !cancelled() }}
+      # run even iff previous step failed
+        if: ${{ !cancelled() && !($fnttarg_id_full) }}
       # dwyn o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
         uses: actions/upload-artifact@v4
         with:
